apiVersion: v1
kind: Service
metadata:
  labels:
    app: console
  name: michael-console
  namespace: openshift-console
spec:
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    targetPort: 453
  selector:
    app: console
    component: ui
